dist: precise
sudo: false
language: php

warnings_are_errors: false

env:
  - WP_VERSION=latest

matrix:
  include:
      - php: 7.2
        env: PHP_UNIT_VERSION=6
      - php: 7.0
        env: PHP_UNIT_VERSION=6
      - php: 5.6
        env: PHP_UNIT_VERSION=4

before_install:
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

install:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar require phpunit/phpunit:^$PHP_UNIT_VERSION

script:
  - WP_TESTS_DIR=/tmp/wordpress-tests-lib/ vendor/bin/phpunit -c phpunit.xml.dist
